extend-include = ["*.ipynb"]

[lint]
select = ["ALL"]
ignore = [
    "INP001",   # implicit-namespace-package
    "COM812",   # TrailingCommaMissing
    "COM819",   # TrailingCommaProhibited
    "T201",     # print found
    "N816",     # mixed-case-variable-in-global-scope
    "PLR2004",  # Magic comparison
]

[lint.pydocstyle]
convention = "numpy"

[lint.flake8-annotations]
ignore-fully-untyped = true # Codebase has no types
